In [117]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
from glob import glob
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical # convert to one-hot-encoding

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers
from tensorflow.keras import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau
%matplotlib inline

import matplotlib.pyplot as plt

In [118]:
labels=[['Actinic_keratoses' ,1],['Basal_cell_carcinoma',1],['Benign_keratosis-like_lesions',0],['Dermatofibroma',0],['Melanocytic_nevi',0],['Vascular_lesions',0],['melanoma',1]]


In [119]:
path="D:/Smart Healthcare/Skin-Lesions-Detection-Deep-learning-main/Skin-Lesions-Detection-Deep-learning-main/Notebooks/test_images/test_1.jpeg"

In [120]:
from PIL import Image

In [121]:
reshaped_image = np.asarray(Image.open(path).resize((64,64), resample=Image.NEAREST).\
                            convert("RGB")).ravel()

C:\Users\91987\AppData\Local\Temp\ipykernel_11920\1616291814.py:1: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  reshaped_image = np.asarray(Image.open(path).resize((64,64), resample=Image.NEAREST).\


In [122]:
reshaped_image.T

array([201, 161, 151, ..., 222, 188, 161], dtype=uint8)

In [123]:
r_mean = np.mean(reshaped_image)
r_std = np.std(reshaped_image)

reshaped_image = (reshaped_image - r_mean)/r_std

In [124]:
reshaped_image

array([ 0.72893711,  0.13265445, -0.01641621, ...,  1.04198551,
        0.53514525,  0.13265445])

In [125]:
reshaped_image=reshaped_image.reshape(1,64,64,3)

In [126]:
reshaped_image.shape

(1, 64, 64, 3)

In [127]:
reshaped_image

array([[[[ 7.28937110e-01,  1.32654452e-01, -1.64162128e-02],
         [ 6.99122977e-01,  1.02840319e-01, -4.62303458e-02],
         [ 9.22728974e-01,  3.86074582e-01,  2.07189784e-01],
         ...,
         [ 1.20596324e+00,  7.43844177e-01,  6.69308844e-01],
         [ 9.22728974e-01,  3.71167515e-01,  1.32654452e-01],
         [ 8.78007775e-01,  3.11539249e-01,  1.47561518e-01]],

        [[ 1.05689257e+00,  6.54401778e-01,  5.50052313e-01],
         [ 1.08670671e+00,  6.84215911e-01,  5.79866446e-01],
         [ 9.37636041e-01,  5.20238180e-01,  3.56260449e-01],
         ...,
         [ 1.38484803e+00,  1.05689257e+00,  8.63100709e-01],
         [ 1.14633497e+00,  6.69308844e-01,  4.45702848e-01],
         [ 1.22087030e+00,  7.14030044e-01,  5.35145246e-01]],

        [[ 1.10161377e+00,  6.24587645e-01,  4.00981648e-01],
         [ 1.13142790e+00,  7.43844177e-01,  5.50052313e-01],
         [ 1.19105617e+00,  7.73658310e-01,  5.94773512e-01],
         ...,
         [ 1.11652084e+0

In [128]:
from tensorflow import keras

In [129]:
model=keras.models.load_model("D:/Smart Healthcare/Skin-Lesions-Detection-Deep-learning-main/Skin-Lesions-Detection-Deep-learning-main/Saved Models/Base.h5")

In [130]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 64, 64, 3)]       0         
                                                                 
 conv2d (Conv2D)             (None, 64, 64, 16)        448       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 32, 32, 16)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 32, 32, 32)        4640      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 16, 16, 32)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 16, 16, 64)        18496 

In [131]:
predictions=model.predict(reshaped_image)

1/1 [==============================] - 0s 53ms/step


In [132]:
predictions

array([[2.9817520e-02, 2.3681913e-02, 5.5646770e-02, 6.9306634e-04,
        8.8228035e-01, 1.2791573e-07, 7.8802062e-03]], dtype=float32)

In [133]:
predIdx=np.argmax(predictions)

In [134]:
labels[predIdx]

['Melanocytic_nevi', 0]